# Generated by Django 3.2.6 on 2026-01-26 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='device_name',
        ),
    ]
